import About from './About'
import Copyright from './Copyright'
import CourseCard from './CourseCard'
import CourseSlider from './CourseSlider'
import DesktopMenu from './DesktopMenu'
import Footer from './Footer'
import FooterLinks from './FooterLinks'
import Header from './Header'
import Newsletter from './Newsletter'
import RichText from './RichText'
import Tags from './Tags'

export { About }
export { Copyright }
export { CourseCard }
export { CourseSlider }
export { DesktopMenu }
export { Footer }
export { FooterLinks }
export { Header }
export { Newsletter }
export { RichText }
export { Tags }
