import AddCircle from './AddCircle'
import ArrowRight from './ArrowRight'
import Calendar from './Calendar'
import Category from './Category'
import ChevronDown from './ChevronDown'
import ChevronRight from './ChevronRight'
import ChevronUp from './ChevronUp'
import Clock from './Clock'
import Close from './Close'
import Duration from './Duration'
import Menu from './Menu'
import Price from './Price'
import Register from './Register'
import Search from './Search'
import Star from './Star'
import Wallet from './Wallet'

export { AddCircle }
export { ArrowRight }
export { Calendar }
export { Category }
export { ChevronDown }
export { ChevronRight }
export { ChevronUp }
export { Clock }
export { Close }
export { Duration }
export { Menu }
export { Price }
export { Register }
export { Search }
export { Star }
export { Wallet }
